# Generated by Django 5.2.6 on 2025-09-28 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyPredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('linear_regression', 'Linear Regression'), ('random_forest', 'Random Forest'), ('neural_network', 'Neural Network')], max_length=50, unique=True)),
                ('r2_score', models.FloatField(default=0.0)),
                ('rmse', models.FloatField(default=0.0)),
                ('mae', models.FloatField(default=0.0)),
                ('mse', models.FloatField(default=0.0)),
                ('is_best', models.BooleanField(default=False)),
                ('model_file_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-r2_score'],
            },
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(max_length=50)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('network_traffic', models.FloatField()),
                ('task_priority', models.IntegerField()),
                ('predicted_energy', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
